pipeline:
  name: Build go-web-docker
  identifier: Build_patrickjburke245_go_web_docker_1724954762059
  projectIdentifier: orcaprotectedharnessproject
  orgIdentifier: default
  stages:
    - stage:
        name: Build
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Echo Welcome Message
                  identifier: Echo_Welcome_Message
                  spec:
                    shell: Sh
                    command: echo "Welcome to Harness CI"
              - step:
                  type: Run
                  name: Run_2
                  identifier: Run_2
                  spec:
                    shell: Sh
                    command: |-
                      docker build -f Dockerfile -t ${IMAGE_NAME} .
                      docker images
                      apt update && apt install -y curl
                      curl -sfL 'https://raw.githubusercontent.com/orcasecurity/orca-cli/main/install.sh' | bash
                      orca-cli -p "orca-project-for-harness-builds" image scan "${IMAGE_NAME}"
                    envVariables:
                      ORCA_SECURITY_API_TOKEN: aHR0cHM6Ly9hcHAudXMub3JjYXNlY3VyaXR5LmlvfHxTYzlvWDB3c0Z1cEp6WlBRYm1BN3hBZjBGVWdYaHh2eQ==
                      IMAGE_NAME: my-risky-container
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
  properties:
    ci:
      codebase:
        connectorRef: account.Github
        repoName: patrickjburke245/go-web-docker
        build: <+input>
